### ISSUE TITLE
Documentation: which java version do you need on linux?

### ISSUE THREAD

**Issue by Robinlovelace** [marcusyoung/opentripplanner#14]
Just tried out the getting started vignette, added to Malcolm's PR.

One thing that would be useful for Linux users like me: specify which java version is needed: it failed on mine:

```
java -version 
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
```

**Comment by marcusyoung** [comment]
You need version 8 currently I believe.

**Comment by Robinlovelace** [comment]
And `openjdk` versions don't work it seems. Oracle Java 8 can be installed on Linux no problem, may be worth stating in the README.
