### ISSUE TITLE
Error checking using checkmate

### ISSUE THREAD

**Issue by marcusyoung** [marcusyoung/opentripplanner#16]
Hi,

I'd like to standardise on using checkmate package for argument checking. See link below for list of checks, which include File IO and OS checks amongst many more:

https://mllg.github.io/checkmate/reference/checkmate-package

I have used it for checks in the `otp_connect()` function as an example. One very good aspect as you'll see from that code is the ability to put the checks in collections, so only a single composite message is returned to the user if there are multiple problems. In addition the code is much cleaner.

Marcus

**Comment by Robinlovelace** [comment]
Looks good - a decent package. `stopifnot()` is a base R option with less features.
