### ISSUE TITLE
Agreeing code style

### ISSUE THREAD

**Issue by marcusyoung** [marcusyoung/opentripplanner#3]
We need to agree a consistent code style, for example, naming of functions and variable names.

## Function names
I had been using the convention of lower case 'otp' followed by the function purpose in camel case, for example: `otpTripDistance`. 

Any thoughts on this?

**Comment by Robinlovelace** [comment]
Indeed. Go to resources on this:

- rOpenSci: https://github.com/Robinlovelace/geocompr/commit/97796747d213f7b9060c8ff930258416bf1fe88e
- tidyverse: http://style.tidyverse.org/
- geocompr style (notable difference `=` vs `<-`): https://github.com/Robinlovelace/geocompr/blob/master/our-style.md

Your choice: it's your pkg!

**Comment by Robinlovelace** [comment]
Regarding the specific question: rOpenSci suggests `snake_case` and I approve. So my suggestion in that case would be `otp_trip_distances()` or just `trip_distances()` but `otp_` is a logical affix to refer to functions that call the OTP java file (other functions can avoid that convention). That would be neat.

**Comment by marcusyoung** [comment]
Thanks for the style links, I will follow those up. Must say that I do now prefer to use `<-` for assignment, despite having thought it very odd to begin with!

As the aim is for this package to be part of the rOpenSci suite, then it would make sense to follow their suggestion on function naming.

**Comment by Robinlovelace** [comment]
+1 to suggestion by @mem48: use the same argument names as OTP does.

Can see logic in matching OTP function names but it's weaker. May be good to distinguish between stuff that OTP does (e.g. all funs starting with `otp_` as I suggested above) and things that the R pkgs does (maybe not starting with `otp_`).

**Comment by marcusyoung** [comment]
Yes I agree regarding argument names, which I think is the approach I was following with my initial script. I agree that functions that query otp would be best to start `otp_` and others not. This is what I have adopted in the `otp_connect` function.
