### ISSUE TITLE
Function to set-up OTP

### ISSUE THREAD

**Issue by Robinlovelace** [marcusyoung/opentripplanner#5]
**Is your feature request related to a problem? Please describe.**

The first barrier in many cases will be set-up. 

**Describe the solution you'd like**

A function like [`install_tensorflow()`](https://github.com/rstudio/tensorflow/blob/master/R/install.R) could help.

**Describe alternatives you've considered**

Ask people to install it manually.

**Additional context**

-

**Comment by marcusyoung** [comment]
This is an interesting idea. Just a few initial thoughts:

- Each user will have their own requirements, from very modest (a town/city) to national or multi-national. So there wouldn't be a default install as such.
- Where would it be installed to? The memory requirements of OTP mean that all but the smallest graphs require a substantial amount of RAM to build, which is likely to exceed that available to a user's local machine. And it is not possible to determine the memory requirement for any particular situation in advance. A cloud install may be the best option for many people. But that would suggest an alternative approach. Docker?
- Data - not an issue for many countries, but getting Transit data in GTFS format is a major headache for the UK.
- Would a demo install be a good idea/good starting point?

**Comment by Robinlovelace** [comment]
> Would a demo install be a good idea/good starting point?

Certainly and would help towards a function to help with it. I believe it's possible but not a priority issue - let's get it up and running and tested first!

**Comment by mem48** [comment]
Due to the difficult of getting UK GTFS I've started another package  https://github.com/mem48/UK2GTFS which will produce GTFS files for the UK, nothing working yet but hopefully something soon.
