### ISSUE TITLE
Proposed external function: otp_isochrone

### ISSUE THREAD

**Issue by marcusyoung** [marcusyoung/opentripplanner#9]
This function will return isochrone geometry as a set of GeoJSON multi-polygons, either from a start location or to an end location. This is only applicable to WALK and/or TRANSIT modes.

A potential enhancement would be to return a styled map.

It is also possible for OTP to return a zipped-shapefile instead of GeoJSON.

**Comment by mem48** [comment]
Can I suggest that we have the option to return a SF data frame as well. The GeoJSON to SF conversion is fairly simple and would allow the user to immediately manipulate the results, rather than having to save and load the file.

**Comment by marcusyoung** [comment]
Yes agreed, and conversion to SF would support the option to return a styled map.

**Comment by mem48** [comment]
I've got an isochrone function in my pull request. https://github.com/marcusyoung/opentripplanner/pull/13 

But there seem to be at least 3 different isochone APIs in OTP.

http://dev.opentripplanner.org/apidoc/1.0.0/resource_LIsochrone.html
http://dev.opentripplanner.org/apidoc/1.0.0/resource_SIsochrone.html
http://dev.opentripplanner.org/apidoc/1.0.0/resource_SimpleIsochrone.html 

I'm currently supporting the LIsochone version ( the same as your tutorial), but any views on if we need to support the others, and what the differences are?

**Comment by marcusyoung** [comment]
@mem48 

AFAIK SIsochrone is old and superseded by LIsocrone. I'm not sure about SimpleIsochrone, that seems to do something rather different. It probably needs investigating further to see if it actually works and does anything useful.  I'm hoping to get a proper look at everything you've been working on next week. One thing to note is that LIsocrone is only valid for transit modes, so the function needs to prevent users requesting with other modes. For background there is a discussion about why that's the case on the Google Group.

**Comment by mem48** [comment]
Useful to know. I'd suggest that we warn rather than block the users from using other modes. I produced some driving isochrones so it does "work" on some level. 

I've been working on you vignettes to help explain the code I've added, mostly rewrite of your excellent tutorial, but using functions rather than having to write code yourself.
